import {ObjectId} from 'mongodb';
import {Document, PaginateModel} from 'mongoose';

export interface PhoneRegion extends Document {
  /**
   * unique ID for document
   */
  _id: ObjectId;

  /**
   * code of phoneRegion
   */
  code: string;

  // generated by mongoose
  /**
   * create time of this document
   */
  createdAt: Date;

  /**
   * update time of this document
   */
  updatedAt: Date;
}

export type PhoneRegionModel = PaginateModel<PhoneRegion>;
