import {ObjectId} from 'mongodb';
import {Document, PaginateModel} from 'mongoose';
import {Workspace} from 'src/modules/Workspace/interfaces';

export interface WorkspacePriceType extends Document {
  /**
   * unique ID for document
   */
  _id: ObjectId;

  workspace: Workspace | Workspace['_id'];

  priceType: string;

  // generated by mongoose
  /**
   * create time of this document
   */
  createdAt: Date;

  /**
   * update time of this document
   */
  updatedAt: Date;
}

export type WorkspacePriceTypeModel = PaginateModel<WorkspacePriceType>;
