import {ObjectId} from 'mongodb';
import {Document, PaginateModel} from 'mongoose';

export interface Dashboard extends Document {
  /**
   * unique ID for document
   */
  _id: ObjectId;

  title: JSON;

  apiUrl: string;

  reload: number;

  // generated by mongoose
  /**
   * create time of this document
   */
  createdAt: Date;

  /**
   * update time of this document
   */
  updatedAt: Date;
}

export type DashboardModel = PaginateModel<Dashboard>;
