apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    # dont push to dockerhub
    push: false
  artifacts:
    - image: haze/web
      context: web
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
          - src: '**/*.ts'
            dest: .
    - image: haze/admin
      context: admin
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
          - src: '**/*.ts'
            dest: .
    - image: haze/api
      context: api
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    