import {ObjectId} from 'mongodb';
import {Document, PaginateModel} from 'mongoose';
import {Order} from 'src/modules/Order/interfaces';

export interface OrderWage extends Document {
  /**
   * unique ID for document
   */
  _id: ObjectId;

  /**
   * associated order
   */
  order: Order | Order['_id'];

  /**
   * currency
   */
  currency: string;

  /**
   * amount that paid to app provider
   */
  amountToApp: number;

  // generated by mongoose
  /**
   * create time of this document
   */
  createdAt: Date;

  /**
   * update time of this document
   */
  updatedAt: Date;
}

export type OrderWageModel = PaginateModel<OrderWage>;
