import {ObjectId} from 'mongodb';
import {Document, PaginateModel} from 'mongoose';

export interface Param extends Document {
  /**
   * unique ID for document
   */
  _id: ObjectId;

  /**
   * key name of the param
   */
  type: string;

  /**
   * brief description
   */
  description: string;

  /**
   * param content
   */
  parameters: any;

  // generated by mongoose
  /**
   * create time of this document
   */
  createdAt: Date;

  /**
   * update time of this document
   */
  updatedAt: Date;
}

export type ParamModel = PaginateModel<Param>;
