import {ObjectId} from 'mongodb';
import {Document, PaginateModel} from 'mongoose';
import {Region} from 'src/modules/Region/interfaces';
import {Workspace} from 'src/modules/Workspace/interfaces';

export interface Address extends Document {
  /**
   * unique ID for document
   */
  _id: ObjectId;
  /** attributes */
  workspace: Workspace | Workspace['_id'];
  refType:
    | 'Users'
    | 'Members'
    | 'Merchants'
    | 'Orders'
    | 'Stores'
    | 'Quotation';
  ref: ObjectId;
  type: string;
  name: string;
  country: Region | Region['_id'];
  state: Region | Region['_id'];
  city: Region | Region['_id'];
  address1: string;
  address2: string;
  postCode: string;
  phone: string;
  geometry: any;
  isDefault: boolean;

  // generated by mongoose
  /**
   * create time of this document
   */
  createdAt: Date;

  /**
   * update time of this document
   */
  updatedAt: Date;
}

export type AddressModel = PaginateModel<Address>;
