import {ObjectId} from 'mongodb';
import {Document, PaginateModel} from 'mongoose';
import {WorkspaceSubscription} from '../../WorkspaceSubscription/interfaces';
import {Workspace} from 'src/modules/Workspace/interfaces';

export interface WorkspaceSubscriptionInvoice extends Document {
  /**
   * unique ID for document
   */
  _id: ObjectId;

  /**
   * associated workspace
   */
  workspace: Workspace | Workspace['_id'];
  /**
   * unique invoice number
   */
  invoiceNo: string;

  /**
   * workspace subscription
   */
  subscription: WorkspaceSubscription | WorkspaceSubscription['_id'];

  /**
   * id of Stripe invoice
   */
  stripeInvoiceId: string;

  /**
   * stripe invoice receipt url
   */
  stripeInvoiceUrl: string;

  /**
   * invoice issing date
   */
  date: Date;

  /**
   * invoice item usage period from
   */
  periodFr: Date;

  /**
   * invoice item usage period to
   */
  periodTo: Date;

  /**
   * invoice currenc
   */
  currency: string;

  /**
   * amount of this invoice
   */
  amount: number;

  /**
   * invoice status, text following Stripe invoice status
   * should be one of 'draft', 'open', 'paid', 'void', 'uncollectable'
   */
  status: string;

  // generated by mongoose
  /**
   * create time of this document
   */
  createdAt: Date;

  /**
   * update time of this document
   */
  updatedAt: Date;
}

export type WorkspaceSubscriptionInvoiceModel =
  PaginateModel<WorkspaceSubscriptionInvoice>;
