version: '3.5'

services:
  admin:
    image: ecomm-admin_staging-dist
    container_name: ecomm-admin_staging-dist
    build:
      context: ../../
      dockerfile: docker/Dockerfile-dist
      args:
        - NPM_TOKEN=${NPM_TOKEN}
        - NODE_ENV=staging
    ports:
      - '3115:80'
    env_file:
      - .env.staging
