version: '3.5'

services:
  admin:
    image: ecomm-admin_staging
    container_name: ecomm-admin_staging
    stdin_open: true
    tty: true
    build:
      context: ../../
      dockerfile: docker/Dockerfile
      args:
        - NPM_TOKEN=${NPM_TOKEN}
    volumes:
      - '../../:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3114:3000'
    env_file:
      - .env.release
