import {ObjectId} from 'mongodb';
import {Document, PaginateModel} from 'mongoose';
import {IUser} from 'src/modules/User';
import {Workspace} from 'src/modules/Workspace/interfaces';
import {Coupon} from 'src/modules/Coupon/interfaces';

export interface CouponLog extends Document {
  /**
   * unique ID for document
   */
  _id: ObjectId;

  /**
   * user that use the coupon
   */
  user: IUser | IUser['_id'];

  /**
   * coupon that being used
   */
  coupon: Coupon | Coupon['_id'];

  workspace: Workspace | Workspace['_id'];

  // generated by mongoose
  /**
   * create time of this document
   */
  createdAt: Date;

  /**
   * update time of this document
   */
  updatedAt: Date;
}

export type CouponLogModel = PaginateModel<CouponLog>;
