import {ObjectId} from 'mongodb';
import {Document, PaginateModel} from 'mongoose';

export interface SalesVolume extends Document {
  /**
   * unique ID for document
   */
  _id: ObjectId;

  time: string;

  currency: string;

  amount: number;

  workspace: ObjectId;

  // generated by mongoose
  /**
   * create time of this document
   */
  createdAt: Date;

  /**
   * update time of this document
   */
  updatedAt: Date;
}

export type SalesVolumeModel = PaginateModel<SalesVolume>;
