import {ObjectId} from 'mongodb';
import {Document, PaginateModel} from 'mongoose';
import {Workspace} from 'src/modules/Workspace/interfaces';

interface VersionHistory {
  version: string;
  releaseDate: string;
  updates: string[];
}

interface VersionInfo {
  latestVersionNo: string;
  latestUpdates: string[];
  nextVersionNo: string;
  releaseDate: string;
  nextUpdates: string[];
  history: VersionHistory;
}

export interface WorkspaceApp extends Document {
  /**
   * unique ID for document
   */
  _id: ObjectId;

  workspace: Workspace | Workspace['_id'];

  name: string;

  productionIOS: VersionInfo;

  productionAndroid: VersionInfo;

  // generated by mongoose
  /**
   * create time of this document
   */
  createdAt: Date;

  /**
   * update time of this document
   */
  updatedAt: Date;
}

export type WorkspaceAppModel = PaginateModel<WorkspaceApp>;
