import {ObjectId} from 'mongodb';
import {Document, PaginateModel} from 'mongoose';

export interface SystemReport extends Document {
  /**
   * unique ID for document
   */
  _id: ObjectId;

  // generated by mongoose
  /**
   * create time of this document
   */
  createdAt: Date;

  /**
   * update time of this document
   */
  updatedAt: Date;
}

export type SystemReportModel = PaginateModel<SystemReport>;
