import {ObjectId} from 'mongodb';
import {Document, PaginateModel} from 'mongoose';
import {Order} from 'src/modules/Order/interfaces';
import {Payment} from 'src/modules/Payment/interfaces';

export interface Checkout extends Document {
  /**
   * unique ID for document
   */
  _id: ObjectId;

  /**
   * checkout status
   */
  status: number;

  /**
   * expiry of this Checkout
   * Checkout wil be failed if expired
   */
  expireAt: Date;

  /**
   * inventory log
   * TODO: add productInventoryLogs
   */

  /**
   * order that checkout
   */
  order: Order | Order['_id'];

  /**
   * payment of order/checkout
   */
  payment: Payment | Payment['_id'];

  // generated by mongoose
  /**
   * create time of this document
   */
  createdAt: Date;

  /**
   * update time of this document
   */
  updatedAt: Date;
}

export type CheckoutModel = PaginateModel<Checkout>;
