import {ObjectId} from 'mongodb';
import {Document, PaginateModel} from 'mongoose';
import {Workspace} from 'src/modules/Workspace/interfaces';
import {IUser} from 'src/modules/User/interfaces';

export interface CustomerEnquiry extends Document {
  /**
   * unique ID for document
   */
  _id: ObjectId;

  /**
   * CustomerEnquiry workspace
   */
  workspace: Workspace | Workspace['_id'];

  /**
   * subject
   */
  subject: string;

  /**
   * phoneRegion
   */
  phoneRegion: string;

  /**
   * phone
   */
  phone: string;

  /**
   * message
   */
  message: string;

  /**
   * email
   */
  email: string;

  /**
   * 是否關注 status
   */
  isFollow: boolean;

  /**
   * 關注人 who Follow
   */
  whoFollow: IUser | IUser['_id'];

  /**
   * 關注時間  follow Time
   */
  followTime: Date;

  /**
   * remarks
   */
  remarks: string;

  // generated by mongoose
  /**
   * create time of this document
   */
  createdAt: Date;

  /**
   * update time of this document
   */
  updatedAt: Date;
}

export type CustomerEnquiryModel = PaginateModel<CustomerEnquiry>;
