import {ObjectId} from 'mongodb';
import {Document, PaginateModel} from 'mongoose';
import {Workspace} from 'src/modules/Workspace/interfaces';
import {LocalizeStringModel} from 'src/core';

export interface Language extends Document {
  /**
   * unique ID for document
   */
  _id: ObjectId;

  /**
   * document id referencing to workspace
   */
  workspace: Workspace | Workspace['_id'];

  name: LocalizeStringModel;

  types: string[];

  isActive: boolean;

  // generated by mongoose
  /**
   * create time of this document
   */
  createdAt: Date;

  /**
   * update time of this document
   */
  updatedAt: Date;
}

export type LanguageModel = PaginateModel<Language>;
