import {ObjectId} from 'mongodb';
import {Document, PaginateModel} from 'mongoose';

export interface ThemeIcons {
  /**
   * facebook
   */

  facebook: string;
  /**
   * youtube
   */
  youtube: string;
  /**
   * instagram
   */
  instagram: string;
  /**
   * search
   */
  search: string;
}

export interface ITheme extends Document {
  /**
   * unique ID for document
   */
  _id: ObjectId;

  /**
   * theme name
   */
  name: string;

  /**
   * theme scope
   */
  scope: string;

  /**
   * theme base Theme
   */
  baseTheme: string;

  /**
   * theme color
   */
  color: any;

  /**
   * theme dimensions
   */
  dimensions: any;

  /**
   * theme icons
   */
  icons: ThemeIcons;

  // generated by mongoose
  /**
   * create time of this document
   */
  createdAt: Date;

  /**
   * update time of this document
   */
  updatedAt: Date;
}

export type IThemeModel = PaginateModel<ITheme>;
