apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-depl
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: haze/api
          env: 
            - name: MONGO_URI
              value: 'mongodb://api-mongo-srv:27017/haze-cms'
---
apiVersion: v1
kind: Service
metadata: 
  name: api-srv
spec:
  # default is cluster ip
  selector:
    app: api
  ports:
    - name: api
      protocol: TCP
      port: 3000
      targetPort: 3000
