import {ObjectId} from 'mongodb';
import {Document, PaginateModel} from 'mongoose';
import {Product} from 'src/modules/Product/interfaces';
import {LocalizeStringModel} from 'src/core';
import {FileMeta} from 'src/modules/File/FileMeta/interfaces';

export interface IProductSpec extends Document {
  /**
   * unique ID for document
   */
  _id: ObjectId;

  product: Product | Product['_id'];

  name: LocalizeStringModel;

  values: SpecValue[];

  icon: FileMeta | FileMeta['_id'];

  activeIcon: FileMeta | FileMeta['_id'];

  // generated by mongoose
  /**
   * create time of this document
   */
  createdAt: Date;

  /**
   * update time of this document
   */
  updatedAt: Date;
}

export interface SpecValue {
  _id: ObjectId;
  name: LocalizeStringModel;
}

export type IProductSpecModel = PaginateModel<IProductSpec>;
