import {ObjectId} from 'mongodb';
import {Document, PaginateModel} from 'mongoose';
import {LocalizeString} from 'src/core';

interface SubscriptionPlanItem {
  /**
   * item id
   */
  item: any;

  /**
   * value for this plan
   */
  value: any;
}

interface SubscriptionPlanPricings {
  /**
   * apiId for this plan pricing
   */
  apiId: string;
  /**
   * currency for this plan pricing
   */
  currency: string;
  /**
   * amount for this plan pricing
   */
  amount: string;
  /**
   * unit for this plan pricing
   */
  unit: string;
}

export interface SubscriptionPlan extends Document {
  /**
   * unique ID for document
   */
  _id: ObjectId;

  /**
   * product Id
   */
  productId: string;

  /**
   * code of the plan
   */
  code: string;

  /**
   * name of the plan
   */
  name: LocalizeString;

  /**
   * plan description
   */
  description: LocalizeString;

  /**
   * unit of plan
   * annual/month..etc
   */
  unit: string;

  /**
   * plan pricings
   */
  pricings: SubscriptionPlanPricings[];

  /**
   * plan detail items
   */
  items: SubscriptionPlanItem[];

  /**
   * plan isActive
   */
  isActive: boolean;

  // generated by mongoose
  /**
   * create time of this document
   */
  createdAt: Date;

  /**
   * update time of this document
   */
  updatedAt: Date;
}

export type SubscriptionPlanModel = PaginateModel<SubscriptionPlan>;
