import {ObjectId} from 'mongodb';
import {Document, PaginateModel} from 'mongoose';

export interface TagImage extends Document {
  /**
   * unique ID for document
   */
  _id: ObjectId;

  text: string;

  image: ObjectId;

  workspace: ObjectId;

  // generated by mongoose
  /**
   * create time of this document
   */
  createdAt: Date;

  /**
   * update time of this document
   */
  updatedAt: Date;
}

export type TagImageModel = PaginateModel<TagImage>;
