import {ObjectId} from 'mongodb';
import {Document, PaginateModel} from 'mongoose';

import {IUser} from 'src/modules/User/interfaces';
import {Workspace} from 'src/modules/Workspace/interfaces';

export interface UserSearchHistory extends Document {
  /**
   * unique ID for document
   */
  _id: ObjectId;

  /**
   * workspace that belongs
   */
  workspace: Workspace | Workspace['_id'];

  /**
   * user of this document
   */
  user: IUser | IUser['_id'];

  /**
   * search keyword
   */
  text: string;

  // generated by mongoose
  /**
   * create time of this document
   */
  createdAt: Date;

  /**
   * update time of this document
   */
  updatedAt: Date;
}

export type UserSearchHistoryModel = PaginateModel<UserSearchHistory>;
