import {ObjectId} from 'mongodb';
import {Document, PaginateModel} from 'mongoose';

export interface Tag extends Document {
  /**
   * unique ID for document
   */
  _id: ObjectId;

  /**
   * hash tag text
   */
  text: string;

  /**
   * collections that contain this tag, used for dynamic populate
   */
  refType: string;

  /**
   * _id of related document, used for dynamic populate
   */
  ref: any;

  // generated by mongoose
  /**
   * create time of this document
   */
  createdAt: Date;

  /**
   * update time of this document
   */
  updatedAt: Date;
}

export type TagModel = PaginateModel<Tag>;
