import {ObjectId} from 'mongodb';
import {Document, PaginateModel} from 'mongoose';
import {IUser} from 'src/modules/User';
import {Workspace} from 'src/modules/Workspace/interfaces';
import {OrderCharge, OrderService} from 'src/modules/Order/interfaces';
import {Address} from 'src/modules/Address/interfaces';
import {Product} from 'src/modules/Product/interfaces';
import {IProductSku} from 'src/modules/Product/submodules/ProductSku/interfaces';
import {OrderContact} from '../../Order/interfaces';
interface QuotationDetail {
  /**
   * product id
   */
  product: Product | Product['_id'];

  /**
   * SKU id
   */
  productSKU: IProductSku | IProductSku['_id'];
  currency: string;

  /**
   * quantity
   */
  qty: number;

  /**
   * amount for this SKU
   */
  amount: number;

  /**
   * remark
   */
  remark: string;
}

export interface Quotation extends Document {
  /**
   * unique ID for document
   */
  _id: ObjectId;

  /**
   * generated quote no.
   */
  quotationNo: string;

  /**
   * client who create order
   */
  client: IUser | IUser['_id'];

  /**
   * item details
   */
  details: QuotationDetail[];

  /**
   * order clinet contact
   */
  contact: OrderContact;

  /**
   * order consignee (receiver) contact
   */
  consignee: OrderContact;

  /**
   * billing addr and person
   */
  billingContact: Address | Address['_id'];

  /**
   * order person contact
   */
  contactAddress: Address | Address['_id'];

  /**
   * order's workspace
   */
  workspace: Workspace | Workspace['_id'];

  orderType: string;
  quotationDate: Date;
  services: OrderService[];
  charge: OrderCharge;
  remarks: string;
  status: number;

  // generated by mongoose
  /**
   * create time of this document
   */
  createdAt: Date;

  /**
   * update time of this document
   */
  updatedAt: Date;
}

export type QuotationModel = PaginateModel<Quotation>;
