import {ObjectId} from 'mongodb';
import {Document, PaginateModel} from 'mongoose';

export interface OrderTime extends Document {
  /**
   * unique ID for document
   */
  _id: ObjectId;

  /**
   * time that order will be expired (scheduleTime + pendingRequestExpireIn)
   */
  pendingRequestExpireAt: Date;

  /**
   * time in ms that the order will be expired
   * countdown in app side, when expired, user can extend the expiry
   */
  pendingRequestExpireIn: number;

  /**
   * time for scheduled order
   */
  scheduleTime: Date;

  /**
   * time in ms the client booked ahead of time
   */
  timeScheduledAhead: number;

  /**
   * duration of rental
   */
  duration: number;

  // generated by mongoose
  /**
   * create time of this document
   */
  createdAt: Date;

  /**
   * update time of this document
   */
  updatedAt: Date;
}

export type OrderTimeModel = PaginateModel<OrderTime>;
