import {ObjectId} from 'mongodb';
import {Document, PaginateModel} from 'mongoose';
import {LocalizeString} from 'src/core';

export interface SubscriptionItem extends Document {
  /**
   * unique ID for document
   */
  _id: ObjectId;

  /**
   * item name
   */
  name: LocalizeString;

  /**
   * detail description
   */
  description: LocalizeString;

  /**
   * item isActive
   */
  isActive: boolean;

  // generated by mongoose
  /**
   * create time of this document
   */
  createdAt: Date;

  /**
   * update time of this document
   */
  updatedAt: Date;
}

export type SubscriptionItemModel = PaginateModel<SubscriptionItem>;
