version: 0.0
os: linux
files:
  - source: /
    destination: /home/deploy/sites/ecomm-cart
permissions:
  - object: /home/deploy/sites/ecomm-cart
    pattern: "**"
    owner: deploy
    group: deploy
    mode: 777
    type:
      - file
  - object: /home/deploy/sites/ecomm-cart
    owner: deploy
    group: deploy
    mode: 777
    type:
      - directory
hooks:
  BeforeInstall:
    - location: deploy_script/before-install.sh
      timeout: 300
      runas: deploy
  AfterInstall:
    - location: deploy_script/after-install.sh
      timeout: 300
      runas: deploy
  ApplicationStart:
    - location: deploy_script/application-start.sh
      timeout: 300
      runas: deploy
